version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    restart: always
    network_mode: host
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - esdata:/usr/share/elasticsearch/data
    environment:
    - discovery.type=single-node
    - cluster.name=jgBay-cluster
    - bootstrap.memory_lock=true
    - "xpack.security.enabled=false"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    restart: always
    network_mode: host
    ports:
    - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.1
    restart: always
    network_mode: host
    ports:
    - "9600:9600"

    environment:
      ELASTICSEARCH_URL: http://localhost:9200
      KIBANA_URL: http://localhost:5601
      LOGSTASH_URL: http://localhost:9600


volumes:
  esdata:
    driver: local